// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BGEContext))]
    [Migration("20220916194552_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessLogic.Models.BoardGame", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("MaxAge")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxDuration")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxPlayerNum")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MinAge")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MinDuration")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MinPlayerNum")
                        .HasColumnType("int unsigned");

                    b.Property<long>("ProducerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("Year")
                        .HasColumnType("int unsigned");

                    b.HasKey("ID");

                    b.HasIndex("ProducerID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BusinessLogic.Models.BoardGameEvent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BeginRegistration")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Cost")
                        .HasColumnType("int unsigned");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Duration")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("EndRegistration")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OrganizerID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Purchase")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("VenueID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("OrganizerID");

                    b.HasIndex("VenueID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("BusinessLogic.Models.EventGame", b =>
                {
                    b.Property<long>("BoardGameID")
                        .HasColumnType("bigint");

                    b.Property<long>("BoardGameEventID")
                        .HasColumnType("bigint");

                    b.HasKey("BoardGameID", "BoardGameEventID");

                    b.HasIndex("BoardGameEventID");

                    b.ToTable("EventGameRelations");
                });

            modelBuilder.Entity("BusinessLogic.Models.FavoriteBoardGame", b =>
                {
                    b.Property<long>("BoardGameID")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerID")
                        .HasColumnType("bigint");

                    b.HasKey("BoardGameID", "PlayerID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("BusinessLogic.Models.Organizer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("URL")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Organizers");
                });

            modelBuilder.Entity("BusinessLogic.Models.Player", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("Rating")
                        .HasColumnType("int unsigned");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BusinessLogic.Models.PlayerRegistration", b =>
                {
                    b.Property<long>("BoardGameEventID")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerID")
                        .HasColumnType("bigint");

                    b.HasKey("BoardGameEventID", "PlayerID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("BusinessLogic.Models.Producer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Deleted = false,
                            Name = "base",
                            Rating = 0L,
                            URL = ""
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.Role", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            RoleID = 0L,
                            RoleName = "guest",
                            UserID = 1L
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Name = "guest",
                            Password = "guest"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.Venue", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("URL")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("BusinessLogic.Models.BoardGame", b =>
                {
                    b.HasOne("BusinessLogic.Models.Producer", "Producer")
                        .WithMany()
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("BusinessLogic.Models.BoardGameEvent", b =>
                {
                    b.HasOne("BusinessLogic.Models.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BusinessLogic.Models.EventGame", b =>
                {
                    b.HasOne("BusinessLogic.Models.BoardGameEvent", "BoardGameEvent")
                        .WithMany()
                        .HasForeignKey("BoardGameEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Models.BoardGame", "BoardGame")
                        .WithMany()
                        .HasForeignKey("BoardGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");

                    b.Navigation("BoardGameEvent");
                });

            modelBuilder.Entity("BusinessLogic.Models.FavoriteBoardGame", b =>
                {
                    b.HasOne("BusinessLogic.Models.BoardGame", "BoardGame")
                        .WithMany()
                        .HasForeignKey("BoardGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGame");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BusinessLogic.Models.PlayerRegistration", b =>
                {
                    b.HasOne("BusinessLogic.Models.BoardGameEvent", "BoardGameEvent")
                        .WithMany()
                        .HasForeignKey("BoardGameEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLogic.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardGameEvent");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BusinessLogic.Models.Role", b =>
                {
                    b.HasOne("BusinessLogic.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
